module.exports = (permission) => {
    return {
        CREATE_INSTANT_INVITE: "Criar um Convite",
        KICK_MEMBERS: "Expulsar Membros",
        BAN_MEMBERS: "Banir Membros",
        ADMINISTRATOR: "Administrador",
        MANAGE_CHANNELS: "Gerenciar Canais",
        MANAGE_GUILD: "Gerenciar Servidor",
        ADD_REACTIONS: "Adicionar Reações",
        VIEW_AUDIT_LOGS: "Ver o Registro de Auditoria",
        PRIORITY_SPEAKER: "Voz Prioritária",
        STREAM: "Vídeo",
        VIEW_CHANNEL: "Ver Canal",
        SEND_MESSAGES: "Enviar Mensagens",
        SEND_TTS_MESSAGES: "Enviar Mensagens Text to Speech",
        MANAGE_MESSAGES: "Gerenciar Mensagens",
        EMBED_LINKS: "Inserir Links",
        ATTACH_FILES: "Anexar Arquivos",
        READ_MESSAGE_HISTORY: "Ver o Histórico de Mensagens",
        MENTION_EVERYONE: "Mencionar Todos",
        USE_EXTERNAL_EMOJIS: "Usar Emojis Externos",
        VIEW_GUILD_INSIGHTS: "Ver Análises do Servidor",
        CONNECT: "Conectar",
        SPEAK: "Falar",
        MUTE_MEMBERS: "Silenciar Membros",
        DEAFEN_MEMBERS: "Ensurdecer Membros",
        MOVE_MEMBERS: "Mover Membros",
        CHANGE_NICKNAME: "Alterar Apelido",
        MANAGE_NICKNAMES: "Gerenciar Apelidos",
        MANAGE_ROLES: "Gerenciar Cargos",
        MANAGE_WEBHOOKS: "Gerenciar WebHooks",
        MANAGE_EMOJIS: "Gerenciar Emojis"
    }[permission]
}
